project/MCIW/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import HomeView, ProfileView, RegisterView



app_name='MCIW'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='pages/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MCIW.urls', namespace='MCIW')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/MCIW/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_picture')

    def __str__(self):
        return f'{self.user.username} Profile'

project/MCIW/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email', 'password1','password2']

class UpdateUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['id','username']

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

project/MCIW/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView

from .forms import RegisterUserForm, UpdateProfileForm, UpdateUserForm


class HomeView(TemplateView):
    template_name = "pages/dashboard.html"
    title = 'MCIW'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class RegisterView(TemplateView):

    template_name = "pages/register.html"
    form = RegisterUserForm
    title = 'Inscription'

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = RegisterUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect("MCIW:login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        context['title'] = self.title
        return context


class ProfileView(UpdateView):

    template_name = "pages/profile.html"
    title = 'Profile'
    success_url = reverse_lazy('MCIW:profile')
    fields = ['username']
    form = UpdateUserForm

    def get_object(self):
        return self.request.user


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        context['title'] = self.title
        return context

    

project/MCIW/templates/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon"type="image/png"href="{% static '/data/icon.png' %}"/>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    <title>{% block title %} {{title}} {% endblock %}</title>
    {% block static_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/input.css' %}"/>
    {% endblock static_css %}
  </head>

  <body id="body-pd">
    {% block navbar %} {% include 'components/navbar.html' %} {% endblock navbar %}

    {% block content %}{% endblock content %}

    {% block static_js %}
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock static_js %} {% block footer %}{% endblock footer %}
  </body>
</html>

project/MCIW/templates/components/navbar.html
{% load static %}

<header class="header" id="header">
  <div class="header__toggle">
    <i class="bx bx-menu" id="header-toggle"></i>
  </div>

  <div class="header__profile">
    {% if user.is_authenticated %}
    <a href="{% url 'MCIW:profile' %} " class="header_profile_name">{{user.username}}</a>
    <div class="header_profile_img">
      <img
        src="{{ user.profile.image.url }}"
        alt="profile"
      />
    </div>
    {% else %}
    <a href="{% url 'MCIW:login' %}" class="header_profile_name">Connexion</a>
    {% endif %}
  </div>
</header>

<div class="l-navbar" id="nav-bar">
  <nav class="nav">
    <div>
      
      <a href="{% url 'MCIW:home'  %}" class="nav__logo {% if server %} active {% endif %} ">
        <img
      src="{% static 'data/icon.png' %}"
      alt="icon"
      height="20px"
      width="20px"
    />
        <span class="nav__logo-name">Serveur</span>
      </a>
      <div class="nav__list">
        <a href="" class="nav__link">
          <i class="bx bx-grid-alt nav__icon"></i>
          <span class="nav__name">Dashboard</span>
        </a>
        <a href="" class="nav__link">
          <i class="bx bx-library nav__icon"></i>
          <span class="nav__name">Plugins</span>
        </a>
        <a href="" class="nav__link">
          <i class="bx bx-map nav__icon"></i>
          <span class="nav__name">Carte</span>
        </a>
        <a href="" class="nav__link">
          <i class="bx bx-folder nav__icon"></i>
          <span class="nav__name">Dossier</span>
        </a>
        <a href="" class="nav__link">
          <i class="bx bx-bar-chart-alt-2 nav__icon"></i>
          <span class="nav__name">Option</span>
        </a>
      </div>
    </div>
    {% if user.is_authenticated %}
    
    <a href="{% url 'MCIW:logout' %}" class="nav__link">
      <i class="bx bx-log-out nav__icon"></i>
      <span class="nav__name">Déconnexion</span>
    </a>

    {% else %}
    
    <a href="{% url 'MCIW:login' %}" class="nav__link">
      <i class="bx bx-log-in nav__icon"></i>
      <span class="nav__name">Connexion</span>
    </a>

    {% endif %}
  </nav>
</div>

project/MCIW/templates/pages/dashboard.html
{% extends "base_site.html" %} 

{% block title %} {{title}} {% endblock %} 

{% block content %}

<h1>{{title}}</h1>

{% endblock content %}

project/MCIW/templates/pages/login.html
{% extends "base_site.html" %} 

{% block navbar %} {% endblock %}
{% block content %}


<div class="center">
    <h1 class="title_form">Connexion</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="field_text">
            <label>Pseudo</label>
            <input type="text" name="username">
        </div>

        <div class="field_text">
            <label>Mot de passe</label>
            <input type="password" name="password">
        </div>

        <div class="field_pass">
            <a href="{% url 'MCIW:register' %}">Incription</a>
        </div>
        <input class="btn btn-primary" type="submit" name="Connexion">
        
    </form>
    {{form.errors}}
</div>



{% endblock content %}

project/MCIW/templates/pages/profile.html
{% extends "base_site.html" %} 

{% block content %}

<div class="card profile">
    <h1>{{user.username}} </h1>
    <img src="{{user.profile.image.url}} " alt="" width="120px">
</div>

<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="">
            <label>{{form.username.label}}</label>
            {{form.username}}
        </div>

        <input class="btn btn-primary" type="submit" name="Update" />
    </form>
</div>

{% endblock content %}

project/MCIW/templates/pages/register.html
{% extends "base_site.html" %} 

{% block navbar %} {% endblock %}
{% block content %}


<div class="center">
    <h1 class="title_form">Inscription</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="field_text">
            <label>{{form.username.label}}</label>
            {{form.username}}
        </div>

        <div class="field_text">
            <label>{{form.password1.label}}</label>
            {{form.password1}}
        </div>

        <div class="field_text">
            <label>{{form.password2.label}}</label>
            {{form.password2}}
        </div>

        <div class="field_pass">
            <a href="{% url 'MCIW:login' %} ">Connexion</a>
        </div>
        <input class="btn btn-primary" type="submit" name="Incription">
        
    </form>
    {{form.errors}}
</div>



{% endblock content %}